### ISSUE TITLE
Reload functionality not working as intended

### ISSUE THREAD

**Issue by pedroalopes** [pgjones/hypercorn#111]
I started working with this library in Python, but I am not able to use the reload functionality for a FastAPI application. I have created the following code example in a file named **test_api.py**. Any help on how to solve this issue could be helpful!

```python
from hypercorn.config import Config
import asyncio
from hypercorn.asyncio import serve
from fastapi import FastAPI

app = FastAPI(
    title="api",
    version="0.1",
    description="my first api",
)

@app.get("/")
def hello():
    return "Hello"

async def main():
    server_config = Config()
    await serve(app, server_config)

asyncio.run(main())
```

**Expected Behavior**
- Application should reload when changes are made to the source code

**Actual Behavior**
- API does not reload and changes do not appear on the running application

**Steps to Reproduce the Problem**
- Run the above code snippet with `hypercorn --bind 0.0.0.0:8000 --reload test_api:app`
- Modify the code as the application is running

Version: Python 3.9.13 and Hypercorn 0.14.3
Platform: Ubuntu 20.04

**Comment by Kromtar** [comment]
It seems to be related to version 0.14.X of Hypercorn. Reading this [issue](https://github.com/pgjones/hypercorn/issues/69), I can confirm that when reverting to version 0.13.2 hot reload works again

**Comment by pedroalopes** [comment]
I tried to rollback to version 0.13.2 but still was not able to enable the reload. According to the issue you referenced, I think it might be because I am using the serve API and starting hypercorn from my python code. I tried running through the console ```hypercorn api:app --reload``` and reload works fine on both 0.13.2 and 0.14.2 versions

**Comment by Kromtar** [comment]
I am also running the server from Python:

```
import asyncio
from hypercorn.config import Config
from hypercorn.asyncio import serve
from multiprocessing import freeze_support
from app import app

if __name__ == "__main__":
    freeze_support()
    customConfig = {
        'use_reloader': True,
        'accesslog': '-',
        "errorlog": '-',
    }
    config = Config.from_mapping(customConfig)
    asyncio.run(serve(app, config))
```

hypercorn = "0.13.2"


I am running a FastAPI server:

from fastapi import FastAPI

```
app = FastAPI()

@app.get("/check")
def check():
    return "ok"
```

fastapi = "^0.94.0"

When I make a change, the hot-reload is executed correctly

**Comment by Exagone313** [comment]
I can also reproduce the issue. I am running hypercorn from Python code and auto reloading works with 0.13.2 but not with 0.14.4.

I do not use `Config.from_mapping` like suggested above, but I am setting the `use_reloader` property of the config object directly (actually by reading some custom environment variable).
```python
config = Config()
config.use_reloader = True
asyncio.run(serve(app, config))
```

**Comment by godjangollc** [comment]
Is already fixed in pull request #148 , we must wait until they merge it into the main branch. I tested it on windows and issue is gone. You can test it and give me feedback in case I need to change anything. I hope it helps.

**Comment by Exagone313** [comment]
The issue still exists in 0.15.0 that just got released.

When saving a file, hypercorn crashes with the error:
```
OSError: [Errno 98] Address already in use
```

**Comment by godjangollc** [comment]
I am reviewing that right now to reproduce the error, if I find anything I'll post it here.

**Comment by godjangollc** [comment]
> Reloading still doesn't work in the version 0.15.0 that just got released.
> 
> When saving a file, hypercorn crashes with the error:
> 
> ```
> OSError: [Errno 98] Address already in use
> ```
> 
> This is also reproduced when running `hypercorn --reload` directly.

I couldn't reproduce the error anymore, can you please provide more context? 
I tried reproducing the error using fastapi, hyperorn v0.15.0, I used the reload command directly a few times and then reload the app by updating the code, I couldn't get the error `OSError: [Errno 98] Address already in use `. Also I used a toml file for the configuration. The toml file looks like:
```toml
certfile="security/certs/cert.pem"
keyfile="security/certs/privkey.pem"
include_server_header = false
use_reloader = true
application_path = 'app.main:app'
bind="127.0.0.1:8000"
quic_bind="0.0.0.0:8000"
pid="hypercorn.pin"
```
this way I couldn't either reproduce the error. So I'm empty in ideas how to reproduce that.

**Comment by Exagone313** [comment]
It's possible that the issue is only happening on Linux, which prevents reuse of a socket address for a short time, unless you set SOCK_REUSEADDR.

**Comment by godjangollc** [comment]
That's already implemented
```python
 #/hypercorn/config/  line 246 to 253
....
if self.workers > 1:
        try:
            sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
        except AttributeError:
            pass
    binding = (host, port)

sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
....
```
When creating a socket if there is more than one worker SO_REUSEPORT option is set and the SO_REUSEADDR option is also set regardless of the situation. So the error you are describing shouldn't happen...If you can provide any other details that can help me to assess the problem better to see if I can find a solution...

**Comment by johachi** [comment]
I'm also having the problem with 

> Reloading still doesn't work in the version 0.15.0 that just got released.
> 
> When saving a file, hypercorn crashes with the error:
> 
> ```
> OSError: [Errno 98] Address already in use
> ```
> 
> This is also reproduced when running `hypercorn --reload` directly.

I'm also having this problem on MacOS. (Inside docker container based on `FROM python:3.12.0`). I will try to share some code in the weekend.
