### ISSUE TITLE
--reload is returning OSError: WinError 10038 when file saved

### ISSUE THREAD

**Issue by LizardLiang** [pgjones/hypercorn#118]
I'm currently working on a project with Fastapi and Hypercorn on Windows 11

I'm having trouble adding "reload" flag to Hypercorn. 

Every time I save my file, I get an OSError like below

![image](https://user-images.githubusercontent.com/12999887/232195717-020df34c-5559-4f1d-a9ac-618cc1f11e93.png)

After I installed Hypercorn version 0.13.2, the problem is no longer exists, everything works as expected

However the version of 0.14.3 does not.

This is the command I used to start the app: `hypercorn -b 0.0.0.0:5000 -k asyncio -w 1 --reload main:app`

Can you please tell me how to fix this?

thanks,

**Comment by GeorgeLPerkins** [comment]
I'm having this issue also.

**Comment by godjangollc** [comment]
Hi here its a way to accomplish the same by using code. I couldn't neither find a way by using the cli instead I needed to read the hypercorn.run.run method and do manually something similar:
`python
import asyncio 
from hypercorn.utils import wait_for_changes
from hypercorn.asyncio import serve

loop = asyncio.new_event_loop() # Create an event loop to handle serve exceptions
    asyncio.set_event_loop(loop)
    loop.set_exception_handler(_exception_handler)
    if settings.DEBUG:
        while True: # This makes the program only to get out by using Keyboard interrupt
            shutdown_event = asyncio.Event() # To be visible in the lambda scope
            def infinite_wait_for_changes():
                wait_for_changes(shutdown_event) 
                shutdown_event.set()
            threading.Thread(
                target=infinite_wait_for_changes,
                daemon=True
            ).start()
            loop.run_until_complete(
                serve(app, hconfig, 
                    shutdown_trigger=shutdown_event.wait, 
                )
            )
    else:
        loop.run_until_complete(
                serve(app, hconfig)
        )
`
This way you have a live reload implemented for development, don't use live reload in production, remove from the code when you use it the settings.DEBUG

**Comment by godjangollc** [comment]
Is already fixed in pull request #148 , we must wait until they merge it into the main branch. I tested it on windows and issue is gone. You can test it and give me feedback in case I need to change anything. I hope it helps.

**Comment by iconberg** [comment]
I still have this WinError 10038 with 0.16.0 on Windows 10 and Python 3.9.7.
With 0.13.2 i can avoid this error.
[hypercorn_error_10038.txt](https://github.com/pgjones/hypercorn/files/13826972/hypercorn_error_10038.txt)

**Comment by godjangollc** [comment]
> I still have this WinError 10038 with 0.16.0 on Windows 10 and Python 3.9.7. With 0.13.2 i can avoid this error. [hypercorn_error_10038.txt](https://github.com/pgjones/hypercorn/files/13826972/hypercorn_error_10038.txt)

version 0.15.0 should fix the main error, but @pgjones says it creates other issues... 0.16.0 did a rollback to the pr where the error was tried to be fixed. I still say, if @pgjones allows it, I will personally  try to fix any error related to this issue. But worst nothing if is rolled back as soon as there is any other error that I didnt see.

**Comment by ArchiDevil** [comment]
Getting this error 0.17.3.
