### ISSUE TITLE
--reload throws exception when script is updated

### ISSUE THREAD

**Issue by elau1004** [pgjones/hypercorn#129]
Every time I save my python script, `hypercorn` throws the following exception (even with  no changes):
```
$ hypercorn fastapi_server:app --reload
[2023-06-16 18:29:14 -0700] [23040] [INFO] Running on http://127.0.0.1:8000 (CTRL + C to quit)
Accept failed on a socket
socket: <asyncio.TransportSocket fd=632, family=2, type=1, proto=6, laddr=('127.0.0.1', 8000)>
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\proactor_events.py", line 860, in loop
    f = self._proactor.accept(sock)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\windows_events.py", line 583, in accept
    self._register_with_iocp(listener)
  File "C:\Program Files\Python311\Lib\asyncio\windows_events.py", line 752, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] The parameter is incorrect
unhandled exception during shutdown
task: <Task finished name='Task-2' coro=<Lifespan.handle_lifespan() done, defined at C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\hypercorn\asyncio\lifespan.py:31> exception=LifespanFailureError('Lifespan failure in shutdown. \'Traceback (most recent call last):\n  File "C:\\Users\\elau1\\.virtualenvs\\API-Service-Example-Uymf8eFB\\Lib\\site-packages\\hypercorn\\asyncio\\run.py", line 230, in _run\n    loop.run_until_complete(main(shutdown_trigger=shutdown_trigger))\n  File "C:\\Program Files\\Python311\\Lib\\asyncio\\base_events.py", line 653, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File "C:\\Users\\elau1\\.virtualenvs\\API-Service-Example-Uymf8eFB\\Lib\\site-packages\\hypercorn\\asyncio\\run.py", line 122, in worker_serve\n    bind = repr_socket_addr(sock.family, sock.getsockname())\n                                         ^^^^^^^^^^^^^^^^^^\nOSError: [WinError 10038] An operation was attempted on something that is not a socket\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "C:\\Users\\elau1\\.virtualenvs\\API-Service-Example-Uymf8eFB\\Lib\\site-packages\\starlette\\routing.py", line 686, in lifespan\n    await receive()\n  File "C:\\Users\\elau1\\.virtualenvs\\API-Service-Example-Uymf8eFB\\Lib\\site-packages\\hypercorn\\asyncio\\lifespan.py", line 92, in asgi_receive\n    return await self.app_queue.get()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Program Files\\Python311\\Lib\\asyncio\\queues.py", line 158, in get\n    await getter\nasyncio.exceptions.CancelledError\n\'')>
Traceback (most recent call last):
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\hypercorn\asyncio\run.py", line 230, in _run
    loop.run_until_complete(main(shutdown_trigger=shutdown_trigger))
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\hypercorn\asyncio\run.py", line 122, in worker_serve
    bind = repr_socket_addr(sock.family, sock.getsockname())
                                         ^^^^^^^^^^^^^^^^^^
OSError: [WinError 10038] An operation was attempted on something that is not a socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\starlette\routing.py", line 686, in lifespan
    await receive()
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\hypercorn\asyncio\lifespan.py", line 92, in asgi_receive
    return await self.app_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\hypercorn\asyncio\lifespan.py", line 43, in handle_lifespan
    await self.app(
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\hypercorn\app_wrappers.py", line 33, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\starlette\middleware\exceptions.py", line 55, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\starlette\routing.py", line 707, in __call__
    await self.lifespan(scope, receive, send)
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\starlette\routing.py", line 690, in lifespan
    await send({"type": "lifespan.shutdown.failed", "message": exc_text})
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\hypercorn\asyncio\lifespan.py", line 104, in asgi_send
    raise LifespanFailureError("shutdown", message["message"])
hypercorn.utils.LifespanFailureError: Lifespan failure in shutdown. 'Traceback (most recent call last):
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\hypercorn\asyncio\run.py", line 230, in _run
    loop.run_until_complete(main(shutdown_trigger=shutdown_trigger))
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\hypercorn\asyncio\run.py", line 122, in worker_serve
    bind = repr_socket_addr(sock.family, sock.getsockname())
                                         ^^^^^^^^^^^^^^^^^^
OSError: [WinError 10038] An operation was attempted on something that is not a socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\starlette\routing.py", line 686, in lifespan
    await receive()
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\hypercorn\asyncio\lifespan.py", line 92, in asgi_receive
    return await self.app_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError
'
Process SpawnProcess-2:
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\hypercorn\asyncio\run.py", line 188, in asyncio_worker
    _run(
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\hypercorn\asyncio\run.py", line 230, in _run
    loop.run_until_complete(main(shutdown_trigger=shutdown_trigger))
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\elau1\.virtualenvs\API-Service-Example-Uymf8eFB\Lib\site-packages\hypercorn\asyncio\run.py", line 122, in worker_serve
    bind = repr_socket_addr(sock.family, sock.getsockname())
                                         ^^^^^^^^^^^^^^^^^^
OSError: [WinError 10038] An operation was attempted on something that is not a socket
```
It doesn't crash out back to the command prompt.  This kind of exceptions scare the hell out of developers.  If it is critical, then it need to handle it more gracefully.  If not, then **don't** show this stack trace.

The following is my script (`fastapi_server.py`):
```
from enum import Enum
from datetime import date, datetime
from typing import List, Optional

from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel, PositiveInt

class TestRecord(BaseModel):
    ID : PositiveInt
    created_on : datetime
    int_value : int

test_records = {
    1: TestRecord(ID=1, created_on=datetime.utcnow() ,int_value=1),
    2: TestRecord(ID=2, created_on=datetime.utcnow() ,int_value=2),
    3: TestRecord(ID=3, created_on=datetime.utcnow() ,int_value=3),
    4: TestRecord(ID=4, created_on=datetime.utcnow() ,int_value=4),
    5: TestRecord(ID=5, created_on=datetime.utcnow() ,int_value=5),
}

app = FastAPI()

@app.get("/")
def test_list() -> dict[str ,dict[int ,TestRecord]]:
    return {"test_records" : test_records}
```
I ran my script with the following:
```
$ hypercorn fastapi_server:app --reload
```
While it is running, just re-save the script and you should see `hypercorn`  produce the above stack trace.

The following is my Windows 11 environment:
**Python**:
``` 
$ python --version
Python 3.11.3
```
**Hypercorn**:
```
$ pip freeze | grep  hypercorn
hypercorn==0.14.3
```

**Comment by Mason-Chou** [comment]
Having the same issue too.

System information:
 ```
Windows 10 Build 19044
Python 3.9.1
hypercorn==0.14.3
```

**Comment by godjangollc** [comment]
Is already fixed in pull request #148 , we must wait until they merge it into the main branch. I tested it on windows and issue is gone. You can test it and give me feedback in case I need to change anything. I hope it helps.

**Comment by joshft91** [comment]
Is this fixed in 0.16.0? I am seeing this exact error on Windows. Using Quart with the latest Hypercorn release.

**Comment by g0di** [comment]
I'm still getting this error on Windows, using hypercorn 0.17.3.
